####################
# Preparing CentOS #
####################
---
- name: Install yum-utils, epel etc
  yum:
    name: "{{ item }}"
    update_cache: yes
    # state: absent
  loop:
    - yum-utils
    - epel-release
    - device-mapper-persistent-data
    - lvm2
    - python3-pip
    - python3
    - python-pip

#################################
# Add repository and GPG Docker #
#################################

- name: Add repository
  yum_repository:
    name: docker-ce.repo
    description: docker-ce.repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

##################
# Install Docker #
##################

- name: Install new packages
  yum:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

########################
# Docker configuration #
########################

- name: Add user to docker group
  user:
     name: "{{ ansible_user }}"
     group: docker
  tags:
    - docker

- name: Docker SDK for Python
  pip:
    name: docker

- name: Start and Enable service Docker
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker
